namenode:
    image: 10.10.8.175:5000/hadoop
    ports: 
        - "50070:50070"
    command: hdfs namenode
    hostname: hdfs-namenode

datanode:
    image: 10.10.8.175:5000/hadoop
    command: hdfs datanode
    ports:
# The host port is randomly assigned by Docker, to allow scaling to multiple DataNodes on the same host
        - "50075"
    links:
        - namenode:hdfs-namenode

secondarynamenode:
    image: 10.10.8.175:5000/hadoop
    command: hdfs secondarynamenode
    ports:
        - "50090:50090"
    links:
        - namenode:hdfs-namenode
